site_name: 大学オープンキャンパス情報アグリテータ
site_description: 大学オープンキャンパス情報の累積・公開
repo_url: https://github.com/mtakahashi1150/univ_info
repo_name: univ_info

docs_dir: docs
site_dir: site

theme:
  name: material
  language: ja
  palette:
    scheme: default
    primary: blue
    accent: light blue

nav:
  - オープンキャンパス情報: index.md

plugins:
  - search:
      lang: ja

markdown_extensions:
  - tables
  - toc
  - md_in_html
